project:
  type: website

website:
  title: "My Explorations with LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://yummyhopper.github.io/comm4190_S24_Using_LLMs_Blog/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


